// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdYjVazBdmeRIUTNC3nmulAmsjUYkLpk',
    appId: '1:897665579339:web:f13986ee4bf9849d7dd0ce',
    messagingSenderId: '897665579339',
    projectId: 'wmsapp-2f86b',
    authDomain: 'wmsapp-2f86b.firebaseapp.com',
    storageBucket: 'wmsapp-2f86b.firebasestorage.app',
    measurementId: 'G-Q74Y7L09YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97qjY8xrt604IgHdXyoKxMHgUdk-gvIw',
    appId: '1:897665579339:android:1227c0f399c111177dd0ce',
    messagingSenderId: '897665579339',
    projectId: 'wmsapp-2f86b',
    storageBucket: 'wmsapp-2f86b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4wz5PI4Xks79Am88gq8IuKFmw9nG5CZk',
    appId: '1:897665579339:ios:cb39992b7c36ca4b7dd0ce',
    messagingSenderId: '897665579339',
    projectId: 'wmsapp-2f86b',
    storageBucket: 'wmsapp-2f86b.firebasestorage.app',
    iosBundleId: 'com.example.wmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4wz5PI4Xks79Am88gq8IuKFmw9nG5CZk',
    appId: '1:897665579339:ios:cb39992b7c36ca4b7dd0ce',
    messagingSenderId: '897665579339',
    projectId: 'wmsapp-2f86b',
    storageBucket: 'wmsapp-2f86b.firebasestorage.app',
    iosBundleId: 'com.example.wmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpdYjVazBdmeRIUTNC3nmulAmsjUYkLpk',
    appId: '1:897665579339:web:f49df7538d5a809d7dd0ce',
    messagingSenderId: '897665579339',
    projectId: 'wmsapp-2f86b',
    authDomain: 'wmsapp-2f86b.firebaseapp.com',
    storageBucket: 'wmsapp-2f86b.firebasestorage.app',
    measurementId: 'G-6R4DBQ624G',
  );
}
